#+ endpoint_in_url: False
#+ description: 由项目名称查询参与者的成果名称
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"


PREFIX poap: <http://purl.org/zhejianglab/irobot-center/ontologies/poap#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>

select DISTINCT ?resname where {
	?s ?p  ?_projectName;
      org:hasMember ?aperson .

    ?aperson poap:hasResult ?res.
    ?res foaf:name ?resname .
}
