#+ endpoint_in_url: False
#+ description: 职位为某某的项目参与者的都有谁。 模板：项目参与者中担任某职位的人叫什么名字。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"
#+   - postName: "工程专员"

PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX org:   <http://www.w3.org/ns/org#>
PREFIX poap:  <http://purl.org/zhejianglab/irobot-center/ontologies/poap#>

SELECT DISTINCT ?personname WHERE {

    ?project foaf:name ?_projectName ;
             org:hasMember ?person .

    ?person foaf:name ?personname ;
            org:holds ?post .

    ?post foaf:name ?_postName .

}
