#+ endpoint_in_url: False
#+ description: 由项目名和某参与者名查询参与者的完整地址
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX locn: <http://www.w3.org/ns/locn#>

SELECT DISTINCT ?fullAddress WHERE {

    ?project foaf:name ?_projectName ;
             org:hasMember ?person .

    ?person locn:address ?address ;
            foaf:name ?_personname .

    ?address locn:fullAddress ?fullAddress .

}
