#+ endpoint_in_url: False
#+ description: 由项目名和某参与者名查询参与者的学位/学历名称。模板：项目中某参与者的学历学位是什么。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"
#+   - personName: "李铁风"

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org:  <http://www.w3.org/ns/org#>
PREFIX bob:  <http://purl.org/zhejianglab/irobot-center/ontologies/bob#>

SELECT DISTINCT ?graduationAwardname WHERE {

    ?project foaf:name ?_projectName ;
             org:hasMember ?person .

    ?person bob:hasGraduation ?graduation ;
            foaf:name ?_personName .

    ?graduation bob:graduationAward ?graduationAward .

    ?graduationAward foaf:name ?graduationAwardname .

}
