#+ endpoint_in_url: False
#+ description: 由项目名称查询所有在此项目上发表文章的人名。模板：发表项目文章的有哪些人。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf:	<http://xmlns.com/foaf/0.1/>
PREFIX org: 	<http://www.w3.org/ns/org#>
PREFIX org-lab: <http://purl.org/zhejianglab/irobot-center/ontologies/org-lab#>
PREFIX poap: 	<http://purl.org/zhejianglab/irobot-center/ontologies/poap#>

SELECT DISTINCT ?personname WHERE {

    ?project foaf:name ?_projectName ;
             org:hasMember ?person ;
             poap:hasResult ?result .

    ?person foaf:name ?personname ;
            poap:hasResult ?result .

    ?result a poap:AcademicPublication .

}
