#+ endpoint_in_url: False
#+ description: 由项目名称查询项目造的机器人的下潜深度。模板：制作的深海机器人的下潜深度是多少。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX irobot: <http://purl.org/zhejianglab/irobot-center/ontologies/irobot#>

SELECT ?submergedDepth WHERE {

	?project foaf:name ?_projectName .

    ?robot foaf:maker ?project ;
           irobot:submergedDepth ?submergedDepth.
}
