#+ endpoint_in_url: False
#+ description: 由项目名称查询所有成果名称。模板：项目成果有哪些。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf:	<http://xmlns.com/foaf/0.1/>
PREFIX poap: 	<http://purl.org/zhejianglab/irobot-center/ontologies/poap#>

SELECT ?resultstr WHERE {

    ?project foaf:name ?_projectName ;
             poap:hasResult ?result .

    ?result foaf:name ?resultstr .

}
