#+ endpoint_in_url: False
#+ description: 由文章名(title)查询全部作者名字。模板：文章作者都有谁。
#+ defaults:
#+   - academicPublicationName: "一种深海软体机器人布放平台装置及方法"

PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX poap:    <http://purl.org/zhejianglab/irobot-center/ontologies/poap#>

select distinct ?personname WHERE {

    ?result foaf:name ?_academicPublicationName ;
            a poap:AcademicPublication .

	  ?person foaf:name ?personname ;
             a foaf:Person;
            poap:hasResult ?result .
}
