#+ endpoint_in_url: False
#+ description: 由项目名称查询所有参与者的姓名(有哪些人参与项目)。模板：参与人有哪些。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>

SELECT ?personname WHERE {

    ?project foaf:name ?_projectName ;
             org:hasMember ?person .

    ?person foaf:name ?personname .

}
