#+ endpoint_in_url: False
#+ description: 由项目名和某参与者名查询参与者的职位名称。 模板：项目参与者李国瑞的职位名称是什么。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX org:   <http://www.w3.org/ns/org#>
PREFIX poap: <http://purl.org/zhejianglab/irobot-center/ontologies/poap#>

SELECT DISTINCT ?postname WHERE {

    ?project foaf:name ?_projectName ;
             org:hasMember ?person .

    ?person org:holds ?post ;
            foaf:name "李国瑞" .
    ?post foaf:name ?postname .

}
