#+ endpoint_in_url: False
#+ description: 由项目名称查询所有参与者的学位/学历。模板：参与者有哪些学历学位。
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX bob: <http://purl.org/zhejianglab/irobot-center/ontologies/bob#>

SELECT DISTINCT ?graduationAwardname WHERE {

    ?project foaf:name ?_projectName ;
             org:hasMember ?person .

    ?person bob:hasGraduation ?graduation .
    ?graduation bob:graduationAward ?graduationAward .

    ?graduationAward foaf:name ?graduationAwardname .
}
